---
language: node_js

notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install: ./scripts/ci/upgrade_docker_compose.sh

install: true

jobs:
  include:
    - stage: lint, pull, build
      script: 'npm ci && npm run lint'
    - stage: lint, pull, build
      script: 'docker-compose build --pull'
    - stage: lint, pull, build
      script: 'docker-compose pull'
    - stage: test
      script: ./scripts/ci/test.sh

deploy:
  provider: script
  script: ./scripts/ci/publish_docker_image.sh
  on:
    branch: master
