---
version: '3.7'

services:
  wait-for:
    build:
      context: .

  web:
    command: "bash -c 'sleep 10 && ruby hello.rb -p 8080'"
    image: mycargus/hello_docker_world:master
    ports:
      - '8080:8080'
